name: LevyStudios
favicon: null
layout_spectrum: 0.30936213699169457
typography_spectrum: 0.06071239220909774
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.24754881509579718
  lightness: 0.37629319494590163
  saturation: 0.8652254350017756
  rhythmicContrast: 0.2538237366825342
purpose: []
